.\" Macros
.ds PX \s-1POSIX\s+1
.de EXAMPLE .\" Format de los ejemplos
.RS 10
.BR "\\$1"
.RE
..

.TH sctp_clientd 0.0.0 "23 de Junio 2020"
.LO 8
.SH NAME
sctp_clientd \- cliente SCTP para el servidor proxy socks 5

.SH SINOPSIS
.HP 10
.B  sctp_clientd
[ POSIX style options ]

.SH OPCIONES

.IP "\fB-h\fR"
Imprime la ayuda y termina.

.IP "\fB\-L\fB \fIdirección-de-management\fR"
Establece la dirección donde está siendo servido el servidor de management. Por defecto escucha únicamente en loopback.

.IP "\fB\-P\fB \fIpuerto-conf\fR"
Puerto SCTP donde está escuchando por conexiones entrantes el servidor de configuración. Por defecto el valor es \fI8080\fR.

.IP "\fB\-v\fB"
Imprime información sobre la versión versión y termina.

